"""add_user_profile

Revision ID: 6ef057a4edd0
Revises: a8e158b08c4f
Create Date: 2026-09-07 17:12:47.134880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ef057a4edd0'
down_revision = 'a8e158b08c4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('job_role_custom', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('tech_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
