"""add_note_view_log

Revision ID: 9714ca5498e8
Revises: a01e10a8523f
Create Date: 2026-09-07 13:30:45.302949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9714ca5498e8'
down_revision = 'a01e10a8523f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_view_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_view_log_note_id'), 'note_view_log', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_view_log_user_id'), 'note_view_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_view_log_user_id'), table_name='note_view_log')
    op.drop_index(op.f('ix_note_view_log_note_id'), table_name='note_view_log')
    op.drop_table('note_view_log')
    # ### end Alembic commands ###
