"""add_note_source_path

Revision ID: a8e158b08c4f
Revises: 9714ca5498e8
Create Date: 2026-09-07 17:03:02.376014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a8e158b08c4f'
down_revision = '9714ca5498e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.create_index(op.f('ix_note_source_path'), 'note', ['source_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_source_path'), table_name='note')
    op.drop_column('note', 'source_path')
    # ### end Alembic commands ###
