"""add_note_imported_digests

Revision ID: fd5fced6db3a
Revises: 6ef057a4edd0
Create Date: 2026-09-07 18:37:44.496971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd5fced6db3a'
down_revision = '6ef057a4edd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('imported_digests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'imported_digests')
    # ### end Alembic commands ###
